# Generated by Django 5.0.1 on 2024-01-03 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="accountawaremodel_ptr",
        ),
        migrations.DeleteModel(
            name="AccountAwareModel",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
